"""ASGI application factory for uvicorn.

This module provides a factory function that uvicorn can use to create
the FastAPI application with proper dependency injection.

Usage:
    uvicorn porterminal.asgi:create_app_from_env --factory
"""

import os

from porterminal.access_path import ACCESS_CODE_ENV, validate_access_code


def create_app_from_env():
    """Create FastAPI app from environment variables.

    This is called by uvicorn when using the --factory flag.
    Environment variables:
        PORTERMINAL_CONFIG_PATH: Path to config file (overrides search)
        PORTERMINAL_CWD: Working directory for PTY sessions
        PORTERMINAL_PASSWORD_HASH: Active password hash supplied by the CLI
        PORTERMINAL_COMPOSE_MODE: Optional compose-mode override
        PORTERMINAL_ACCESS_CODE: Per-launch capability path generated by the CLI

    Config search order (when env var not set):
        1. ptn.yaml in cwd
        2. .ptn/ptn.yaml in cwd
        3. ~/.ptn/ptn.yaml
    """
    from porterminal.app import create_app

    raw_access_code = os.environ.get(ACCESS_CODE_ENV)
    if raw_access_code is None:
        raise RuntimeError("Missing per-launch access code; start Porterminal with `ptn`")
    access_code = validate_access_code(raw_access_code)

    # The application lifespan performs environment-aware composition exactly
    # once. Tests and embedders can still inject a precomposed container through
    # porterminal.app.create_app(container, access_code=...).
    return create_app(access_code=access_code)
